In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parents[0] 
sys.path.append(str(PROJECT_ROOT))

from src.load_data import load_all_raw

# Configure matplotlib
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

# Set max columns to display
pd.set_option('display.max_columns', None)

# Create folder for images
os.makedirs(PROJECT_ROOT / 'images/images_before', exist_ok=True)

In [57]:
bh_raw, ir_raw = load_all_raw()

📁 Reading file: D:\Documents\DSEB\Data Prep and Visualization\final_prj\DPnV_Group5_DSEB\data\raw\2021_HC_NATIONAL_MASTER_FILE.txt
  ✅ Parsed 26,136 BH records, 11,064 IR records.

📁 Reading file: D:\Documents\DSEB\Data Prep and Visualization\final_prj\DPnV_Group5_DSEB\data\raw\2022_HC_NATIONAL_MASTER_FILE.txt
  ✅ Parsed 26,136 BH records, 11,898 IR records.

📁 Reading file: D:\Documents\DSEB\Data Prep and Visualization\final_prj\DPnV_Group5_DSEB\data\raw\2023_HC_NATIONAL_MASTER_FILE.txt
  ✅ Parsed 26,136 BH records, 12,034 IR records.

📁 Reading file: D:\Documents\DSEB\Data Prep and Visualization\final_prj\DPnV_Group5_DSEB\data\raw\2024_HC_NATIONAL_MASTER_FILE.txt
  ✅ Parsed 26,136 BH records, 11,679 IR records.
==================================================
 TOTAL RECORDS LOADED:
   BH (Agency) records: 104,544
   IR (Incident) records: 46,675
==================================================

In [67]:
bh_decoded = pd.read_parquet('../data/interim/bh_decoded.parquet')
ir_decoded = pd.read_parquet('../data/interim/ir_decoded.parquet')

In [91]:
df_before = ir_decoded.merge(
        bh_decoded, 
        left_index=True,
        right_index=True,
        how='left',
        suffixes=('', '_agency')
    )
df_before.head()

,record_type,state_code,ori,incident_number,incident_date,data_source,quarter,total_victims,total_offenders,offender_race,ucr_offense_code_1,num_victims_1,location_1,bias_motivation_1a,victim_types_1,ucr_offense_code_2,num_victims_2,location_2,bias_motivation_2a,victim_types_2,ucr_offense_code_3,num_victims_3,location_3,bias_motivation_3a,victim_types_3,ucr_offense_code_4,num_victims_4,location_4,bias_motivation_4a,victim_types_4,ucr_offense_code_5,num_victims_5,location_5,bias_motivation_5a,victim_types_5,ucr_offense_code_6,num_victims_6,location_6,bias_motivation_6a,victim_types_6,ucr_offense_code_7,num_victims_7,location_7,bias_motivation_7a,victim_types_7,ucr_offense_code_8,num_victims_8,location_8,bias_motivation_8a,victim_types_8,ucr_offense_code_9,num_victims_9,location_9,bias_motivation_9a,victim_types_9,ucr_offense_code_10,num_victims_10,location_10,bias_motivation_10a,victim_types_10,bias_motivation_1b,bias_motivation_1c,bias_motivation_1d,bias_motivation_1e,bias_motivation_2b,bias_motivation_2c,bias_motivation_2d,bias_motivation_2e,bias_motivation_3b,bias_motivation_3c,bias_motivation_3d,bias_motivation_3e,bias_motivation_4b,bias_motivation_4c,bias_motivation_4d,bias_motivation_4e,bias_motivation_5b,bias_motivation_5c,bias_motivation_5d,bias_motivation_5e,bias_motivation_6b,bias_motivation_6c,bias_motivation_6d,bias_motivation_6e,bias_motivation_7b,bias_motivation_7c,bias_motivation_7d,bias_motivation_7e,bias_motivation_8b,bias_motivation_8c,bias_motivation_8d,bias_motivation_8e,bias_motivation_9b,bias_motivation_9c,bias_motivation_9d,bias_motivation_9e,bias_motivation_10b,bias_motivation_10c,bias_motivation_10d,bias_motivation_10e,num_adult_victims,num_juvenile_victims,num_adult_offenders,num_juvenile_offenders,offender_ethnicity,bh_index,file_id,_ir_line_no,state_name,offense_1,bias_1a_category,bias_1b_category,bias_1c_category,bias_1d_category,bias_1e_category,offense_2,bias_2a_category,bias_2b_category,bias_2c_category,bias_2d_category,bias_2e_category,offense_3,bias_3a_category,bias_3b_category,bias_3c_category,bias_3d_category,bias_3e_category,offense_4,bias_4a_category,bias_4b_category,bias_4c_category,bias_4d_category,bias_4e_category,offense_5,bias_5a_category,bias_5b_category,bias_5c_category,bias_5d_category,bias_5e_category,offense_6,bias_6a_category,bias_6b_category,bias_6c_category,bias_6d_category,bias_6e_category,offense_7,bias_7a_category,bias_7b_category,bias_7c_category,bias_7d_category,bias_7e_category,offense_8,bias_8a_category,bias_8b_category,bias_8c_category,bias_8d_category,bias_8e_category,offense_9,bias_9a_category,bias_9b_category,bias_9c_category,bias_9d_category,bias_9e_category,offense_10,bias_10a_category,bias_10b_category,bias_10c_category,bias_10d_category,bias_10e_category,record_type_agency,state_code_agency,ori_agency,date_ori_added,date_ori_went_nibrs,city_name,state_abbr,population_group,country_division,country_region,agency_type,is_core_city,covered_by_ori,fbi_field_office,judicial_district,is_nibrs_active,inactive_date,current_population_1,ucr_county_code_1,msa_code_1,last_population_1,current_population_2,ucr_county_code_2,msa_code_2,last_population_2,current_population_3,ucr_county_code_3,msa_code_3,last_population_3,current_population_4,ucr_county_code_4,msa_code_4,last_population_4,current_population_5,ucr_county_code_5,msa_code_5,last_population_5,master_file_year,state_q1_activity,state_q2_activity,state_q3_activity,state_q4_activity,federal_q1_activity,federal_q2_activity,federal_q3_activity,federal_q4_activity,agency_name,fips_counties_1,fips_counties_2,fips_counties_3,fips_counties_4,fips_counties_5,bh_index_agency,file_id_agency,state_name_agency
0,IR,50,AK0010100,2W2MGU73SXX8,20210527,Unknown,2,001,00,Unknown,290,001,Highway/Road/Alley,Anti-Hispanic or Latino,Individual,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,000,001,00,00,Unknown,0,2021,2,Alaska,Destruction/Damage/Vandalism of Property,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,BH,50,AK0010100,,,ANCHORAGE,AK,"Cities 250,000-499,999",Pacific,West,City,True,,3030,All of the state,False,,000286238,00,39,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,2021,Zero-Report (no incident),Incident Report submitted,Incident Report submitted,Incident Report submitted,No information submitted,No information submitted,No information submitted,No information submitted,ANCHORAGE,020,,,,,0,2021,Alaska
1,IR,50,AK0010100,2W2MGU73SY2,20210525,Unknown,2,000,01,White,290,001,Bar/Nightclub,Anti-LGBTQ+ (Mixed Group),Business,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,000,000,00,01,Unknown,0,2021,3,Alaska,Destruction/Damage/Vandalism of Property,Sexual Orientation,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,BH,50,AK0010200,,20210101,FAIRBANKS,AK,"Cities 25,000-49,999",Pacific,West,City,True,,3030,All of the state,True,,000030598,00,258,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,2021,Zero-Report (no incident),Zero-Report (no incident),Incident Report submitted,Zero-Report (no incident),No information submitted,No information submitted,No information submitted,No information submitted,FAIRBANKS,090,,,,,1,2021,Alaska
2,IR,50,AK0010100,2W2MGU82JNB4,20210825,Unknown,3,003,01,White,13C,001,Residence/Home,Anti-Asian,Individual,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,001,002,01,00,Unknown,0,2021,4,Alaska,Intimidation,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,BH,50,AK0010300,,20221001,JUNEAU,AK,"Cities 25,000-49,999",Pacific,West,City,False,,3030,All of the state,True,,000031874,00,0,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,2021,No information submitted,Incident Report submitted,No information submitted,Incident Report submitted,No information submitted,No information submitted,No information submitted,No information submitted,JUNEAU,110,,,,,2,2021,Alaska
3,IR,50,AK0010100,2W2MGU82S468,20211104,Unknown,4,000,00,Unknown,290,001,Church/Synagogue/Temple,Anti-Catholic,Religious Organization,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,000,000,00,00,Unknown,0,2021,5,Alaska,Destruction/Damage/Vandalism of Property,Religion,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,BH,50,AK0010400,,20210101,KETCHIKAN,AK,"Cities 2,500-9,999",Pacific,West,City,False,,3030,All of the state,True,,000008198,00,0,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,2021,Zero-Report (no incident),Zero-Report (no incident),Zero-Report (no incident),Incident Report submitted,No information submitted,No information submitted,No information submitted,No information submitted,KETCHIKAN,130,,,,,3,2021,Alaska
4,IR,50,AK0010100,PT-0WE0W4HCT,20210429,Unknown,2,001,02,American Indian/Alaska Native,13A,001,Highway/Road/Alley,Anti-Gay (Male),Individual,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,001,000,02,00,Not Hispanic or Latino,0,2021,6,Alaska,Aggravated Assault,Sexual Orientation,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,BH,50,AK0010500,,20210101,KODIAK,AK,"Cities 2,500-9,999",Pacific,West,City,False,,3030,All of the state,True,,000005776,00,0,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,000000000,,,000000000,2021,Zero-Report (no incident),Zero-Report (no incident),Zero-Report (no incident),Zero-Report (no incident),No information submitted,No information submitted,No information submitted,No information submitted,KODIAK,150,,,,,4,2021,Alaska

In [92]:
"""
BEFORE MODEL (BAD PIPELINE)
--------------------------------------
Predict race-bias (1) vs non-race-bias (0)
Using raw data without cleaning or enrichment
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# ===========================================
# Load the decoded but uncleaned dataset
# ===========================================

# -------------------------------------------
# 1. Target Variable (Raw Bias Category)
# -------------------------------------------
df_before["bias_raw"] = df_before["bias_1a_category"].astype(str)

df_before["target_race_bias"] = df_before["bias_raw"].apply(
    lambda x: 1 if x == "Race/Ethnicity" else 0
)

# -------------------------------------------
# 2. Basic Dirty Features
# -------------------------------------------
before_features = [
    "offense_1",
    "location_1",
    "total_victims",
    "total_offenders",
    "state_name",
    "country_region",
    "country_division"
]

df_before = df_before[before_features + ["target_race_bias"]].dropna()

# -------------------------------------------
# 3. BAD ENCODING (LabelEncoder Everything)
# -------------------------------------------
le = LabelEncoder()

for col in before_features:
    df_before[col] = df_before[col].astype(str)
    df_before[col] = le.fit_transform(df_before[col])

# -------------------------------------------
# 4. Train/Test Split
# -------------------------------------------
X = df_before[before_features]
y = df_before["target_race_bias"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# -------------------------------------------
# 5. BAD MODEL
# -------------------------------------------
model_before = LogisticRegression(max_iter=300)
model_before.fit(X_train, y_train)

y_pred_before = model_before.predict(X_test)

print("\n=== BEFORE CLEANING MODEL RESULTS ===")
print(classification_report(y_test, y_pred_before))
print(confusion_matrix(y_test, y_pred_before))

=== BEFORE CLEANING MODEL RESULTS ===
              precision    recall  f1-score   support

           0       0.58      0.20      0.29      5041
           1       0.59      0.89      0.71      6474

    accuracy                           0.59     11515
   macro avg       0.58      0.54      0.50     11515
weighted avg       0.58      0.59      0.53     11515

[[ 989 4052]
 [ 724 5750]]

In [80]:
df["bias_1a_category"].value_counts()

bias_1a_category
Race/Ethnicity        26315
Religion               9455
Sexual Orientation     8013
Gender Identity        1799
Disability              698
Gender                  395
Name: count, dtype: int64

In [93]:
"""
AFTER MODEL (GOOD PIPELINE)
---------------------------------------------
Predict race-bias (1) vs non-race-bias (0)
Using the fully cleaned & enriched dataset
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# ===========================================
# Load cleaned + enriched dataset
# ===========================================
df = pd.read_parquet("../data/processed/hatecrimes_enriched.parquet")

# -------------------------------------------
# 1. Target Variable
# -------------------------------------------
df["target_race_bias"] = df["bias_1a_category"].apply(
    lambda x: 1 if x == "Race/Ethnicity" else 0
)

# -------------------------------------------
# 2. Feature Selection
# -------------------------------------------
after_features = [
    "offense_1",
    "location_1",
    "total_victims",
    "total_offenders",
    "victim_offender_ratio",
    "year",
    "month",
    "day_of_week",
    "is_weekend",
    "state_name",
    "state_population",
    "country_region",
    "country_division"
]

df_after = df[after_features + ["target_race_bias"]].dropna(subset=["target_race_bias"])

# Remove extreme victim/offender outliers
df_after = df_after[df_after["total_victims"] <= 20]
df_after = df_after[df_after["total_offenders"] <= 20]

# -------------------------------------------
# 3. Column Groups
# -------------------------------------------
categorical_cols = [
    "offense_1",
    "location_1",
    "day_of_week",
    "state_name",
]

numeric_cols = [
    "total_victims",
    "total_offenders",
    "victim_offender_ratio",
    "year",
    "month",
    "is_weekend",
    "state_population",
]

X = df_after[after_features].copy()
y = df_after["target_race_bias"]

# Replace pd.NA with np.nan (sklearn-safe)
X = X.replace({pd.NA: np.nan})

# -------------------------------------------
# 4. Preprocessing Pipeline
# -------------------------------------------
preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", SimpleImputer(strategy="median"), numeric_cols),
    ],
    remainder="drop"
)

# -------------------------------------------
# 5. Full Model Pipeline
# -------------------------------------------
model_after = Pipeline(
    steps=[
        ("preprocess", preprocess),
        ("clf", RandomForestClassifier(
            n_estimators=300,
            max_depth=20,
            min_samples_split=5,
            random_state=42
        ))
    ]
)

# -------------------------------------------
# 6. Train/Test Split
# -------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

# -------------------------------------------
# 7. Train Model
# -------------------------------------------
model_after.fit(X_train, y_train)
y_pred_after = model_after.predict(X_test)

print("\n=== AFTER CLEANING MODEL RESULTS ===")
print(classification_report(y_test, y_pred_after))
print(confusion_matrix(y_test, y_pred_after))

=== AFTER CLEANING MODEL RESULTS ===
              precision    recall  f1-score   support

           0       0.70      0.37      0.49      5098
           1       0.64      0.88      0.74      6569

    accuracy                           0.66     11667
   macro avg       0.67      0.62      0.61     11667
weighted avg       0.67      0.66      0.63     11667

[[1896 3202]
 [ 816 5753]]

In [79]:
y_test.value_counts()

target_race_bias
0    11667
Name: count, dtype: int64

In [53]:
enriched = pd.read_parquet('../data/processed/hatecrimes_enriched.parquet')
enriched.head()

,file_id,bh_index,ori,incident_number,incident_date,year,quarter,month,day_of_week,is_weekend,total_victims,num_adult_victims,num_juvenile_victims,total_offenders,num_adult_offenders,num_juvenile_offenders,victim_offender_ratio,offender_race,offender_ethnicity,state_code,state_abbr,state_name,agency_name,agency_type,date_ori_went_nibrs,master_file_year,city_name,is_core_city,population_group,country_division,country_region,judicial_district,current_population,offense,offense_severity,num_victims,victim_types,location,bias_motivation_a,bias_a_category,bias_motivation_b,bias_b_category,bias_motivation_c,bias_c_category,bias_motivation_d,bias_d_category,bias_motivation_e,bias_e_category,offense_index,state_population
0,2021,441,AL0520100,AL0520100-GM5B8LZG Q8F-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,Black or African American,Not Hispanic or Latino,01,AL,Alabama,DECATUR,City,2021-01-01,2021,Decatur,True,"Cities 50,000-99,999",East South Central,South,Northern,54240,Arson,Medium,1,Individual,Residence/Home,Anti-White,Race/Ethnicity,None,None,None,None,None,None,None,None,1,5049196
1,2021,1065,AZ0080000,AZ0080000-V2-IYBRWSU72-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,02,AZ,Arizona,MOHAVE,County,2020-10-01,2021,Kingman,False,"MSA Counties 25,000-99,999",Mountain,West,All of the state,74698,Robbery,High,1,Individual,Residence/Home,Anti-Church of Jesus Christ (LDS),Religion,None,None,None,None,None,None,None,None,1,7274078
2,2021,1482,CA0191900,CA0191900-0819PU72ZPX8-0,2021-01-01,2021,Q1,1,Friday,False,2,2,0,1,1,0,2.0,White,Not Hispanic or Latino,04,CA,California,CERRITOS,City,NaT,2021,Monterey Park,False,"Cities 25,000-49,999",Pacific,West,Central,48583,Intimidation,Low,1,Individual,Residence/Home,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,1,39142565
3,2021,1788,CA0331300,CA0331300-CN0BRVSQT28N-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,04,CA,California,RIVERSIDE,City,2023-01-01,2021,Riverside,True,"Cities 250,000-499,999",Pacific,West,Central,333437,Aggravated Assault,High,1,Individual,Highway/Road/Alley,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,1,39142565
4,2021,1864,CA0350100,CA0350100-NM-U72841AEM-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,Unknown,Hispanic or Latino,04,CA,California,HOLLISTER,City,2021-02-01,2021,Hollister,False,"Cities 25,000-49,999",Pacific,West,Northern,42505,Intimidation,Low,1,Individual,Restaurant,Anti-Gay (Male),Sexual Orientation,None,None,None,None,None,None,None,None,1,39142565

In [55]:
a = enriched.groupby('incident_number')
a.head(10)

,file_id,bh_index,ori,incident_number,incident_date,year,quarter,month,day_of_week,is_weekend,total_victims,num_adult_victims,num_juvenile_victims,total_offenders,num_adult_offenders,num_juvenile_offenders,victim_offender_ratio,offender_race,offender_ethnicity,state_code,state_abbr,state_name,agency_name,agency_type,date_ori_went_nibrs,master_file_year,city_name,is_core_city,population_group,country_division,country_region,judicial_district,current_population,offense,offense_severity,num_victims,victim_types,location,bias_motivation_a,bias_a_category,bias_motivation_b,bias_b_category,bias_motivation_c,bias_c_category,bias_motivation_d,bias_d_category,bias_motivation_e,bias_e_category,offense_index,state_population
0,2021,441,AL0520100,AL0520100-GM5B8LZG Q8F-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,Black or African American,Not Hispanic or Latino,01,AL,Alabama,DECATUR,City,2021-01-01,2021,Decatur,True,"Cities 50,000-99,999",East South Central,South,Northern,54240,Arson,Medium,1,Individual,Residence/Home,Anti-White,Race/Ethnicity,None,None,None,None,None,None,None,None,1,5049196
1,2021,1065,AZ0080000,AZ0080000-V2-IYBRWSU72-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,02,AZ,Arizona,MOHAVE,County,2020-10-01,2021,Kingman,False,"MSA Counties 25,000-99,999",Mountain,West,All of the state,74698,Robbery,High,1,Individual,Residence/Home,Anti-Church of Jesus Christ (LDS),Religion,None,None,None,None,None,None,None,None,1,7274078
2,2021,1482,CA0191900,CA0191900-0819PU72ZPX8-0,2021-01-01,2021,Q1,1,Friday,False,2,2,0,1,1,0,2.0,White,Not Hispanic or Latino,04,CA,California,CERRITOS,City,NaT,2021,Monterey Park,False,"Cities 25,000-49,999",Pacific,West,Central,48583,Intimidation,Low,1,Individual,Residence/Home,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,1,39142565
3,2021,1788,CA0331300,CA0331300-CN0BRVSQT28N-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,04,CA,California,RIVERSIDE,City,2023-01-01,2021,Riverside,True,"Cities 250,000-499,999",Pacific,West,Central,333437,Aggravated Assault,High,1,Individual,Highway/Road/Alley,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,1,39142565
4,2021,1864,CA0350100,CA0350100-NM-U72841AEM-0,2021-01-01,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,Unknown,Hispanic or Latino,04,CA,California,HOLLISTER,City,2021-02-01,2021,Hollister,False,"Cities 25,000-49,999",Pacific,West,Northern,42505,Intimidation,Low,1,Individual,Restaurant,Anti-Gay (Male),Sexual Orientation,None,None,None,None,None,None,None,None,1,39142565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48671,2024,13365,NC0430000,NC0430000-CE0B0MTL728N-0,2024-01-26,2024,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,32,NC,North Carolina,HARNETT,County,2020-01-01,2024,Lillington,False,"Non-MSA Counties 100,000+",South Atlantic,South,Eastern,118346,Destruction/Damage/Vandalism of Property,Low,1,Individual,Residence/Home,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,4,11046024
48672,2024,15219,NY0010100,NY0010100-CE0DEOBH728N-0,2024-05-29,2024,Q2,5,Wednesday,False,2,2,0,1,1,0,2.0,White,Unknown,31,NY,New York,ALBANY,City,2020-11-01,2024,Albany,True,"Cities 100,000-249,999",Middle Atlantic,Northeast,Northern,102095,Drug/Narcotic Violations,Medium,1,Society/Public,Restaurant,Anti-Asian,Race/Ethnicity,None,None,None,None,None,None,None,None,4,19867248
48673,2024,23961,UT0271000,UT0271000-ZIZJ4V44BF39-0,2024-06-18,2024,Q2,6,Tuesday,False,4,4,0,1,1,0,4.0,White,Not Hispanic or Latino,43,UT,Utah,WASHINGTON,City,2006-01-01,2024,Washington,False,"Cities 25,000-49,999",Mountain,West,All of the state,35835,Weapon Law Violations,Medium,1,Society/Public,Residence/Home,Anti-LGBTQ+ (Mixed Group),Sexual Orientation,None,None,None,None,None,None,None,None,4,3503613
48674,2022,12861,NB0740100,NB0740100-KB2TYGRYBC72-0,2022-06-08,2022,Q2,6,Wednesday,False,2,2,0,1,1,0,2.0,White,Unknown,26,NB,Nebraska,FALLS CITY,City,2015-11-01,2022,Falls City,False,"Cities 2,500-9,999",West North Central,North Central,All of the state,4032,Weapon Law Violations,Medium,1,Society/Public,Hotel/Motel/Etc.,"Anti-Multiple Races, Group",Race/Ethnicity,None,None,None,None,None,None,None,None,5,1972246
48675,2023,9288,MA0093000,MA0093000-C60BIMBV728N-0,2023-02-23,2023,Q1,2,Thursday,False,4,4,0,4,0,4,1.0,Unknown,Multiple Ethnicities,20,MA,Massachusetts,MEDFORD,City,2013-01-01,2023,Medford,False,"Cities 50,000-99,999",New England,Northeast,All of the state,68280,Other Larceny,Low,1,Individual,Commercial/Office Building,Anti-Mental Disability,Disability,None,None,None,None,None,None,None,None,5,7066568

In [54]:
len(enriched)

48676

In [44]:
enriched['state_code'].value_counts(dropna=False)

state_code
04    7856
29    4384
31    3665
46    2157
42    2052
20    1882
34    1757
21    1653
36    1207
37    1178
12    1163
32    1137
05    1103
19     946
45     928
02     904
01     892
09     878
24     848
22     817
10     663
13     633
08     572
48     524
16     522
15     484
98     473
27     456
43     441
39     395
41     392
06     378
17     320
14     318
35     292
18     259
47     243
51     234
26     212
30     210
44     192
11     182
28     133
33      97
03      94
38      88
50      86
49      83
23      77
40      74
07      62
25      53
55      26
Name: count, dtype: int64

In [51]:
enriched['current_population'].isnull().sum()

np.int64(3486)

In [25]:
a = enriched[enriched['offender_race'] == 'Unknown']['total_offenders']
len(a[a == 0])

17094

In [26]:
a[a != 0]

4        1
16       1
38       1
69       2
149      1
        ..
46607    2
46630    1
46644    1
46648    1
46660    2
Name: total_offenders, Length: 2455, dtype: Int64

offense_1: 2 None

In [58]:
enriched['total_offenders'].value_counts(dropna=False)

total_offenders
1     23308
0     19274
2      2832
3       771
4       287
5       106
6        33
7        21
8        21
9         9
15        4
11        3
10        3
13        1
32        1
25        1
Name: count, dtype: Int64

In [72]:
enriched['bias_1a_category'].value_counts(dropna=False)

bias_1a_category
Race/Ethnicity        26315
Religion               9455
Sexual Orientation     8013
Gender Identity        1799
Disability              698
Gender                  395
Name: count, dtype: int64

In [10]:
df['state_name'].nunique()

53

In [12]:
df['state_name'].value_counts().sum()

np.int64(46675)

In [33]:
STATE_POP_FILE = PROJECT_ROOT / "data" / "external_data" / "state_population_21-24.xlsx"
TERR_FILE = PROJECT_ROOT / "data" / "external_data" / "territories_population_21-24.csv"

df_states = pd.read_excel(STATE_POP_FILE, skiprows=3, nrows=57)

# Drop total and regions rows
exclude = ["United States", "Northeast", "Midwest", "South", "West"]
df_states = df_states[~df_states["Geographic Area"].isin(exclude)]

df_states = df_states.rename(columns={"Geographic Area": "state_name"})

# Reshape df_state
df_states_long = df_states.melt(
    id_vars="state_name",
    value_vars=[2021, 2022, 2023, 2024],
    var_name="year",
    value_name="state_population"
)
df_states_long

        state_name  year  state_population
0          Alabama  2021           5049196
1           Alaska  2021            734420
2          Arizona  2021           7274078
3         Arkansas  2021           3026870
4       California  2021          39142565
..             ...   ...               ...
203     Washington  2024           7958180
204  West Virginia  2024           1769979
205      Wisconsin  2024           5960975
206        Wyoming  2024            587618
207    Puerto Rico  2024           3203295

[208 rows x 3 columns]

In [34]:
df_territories = pd.read_csv(TERR_FILE)
df_territories

        state_name  year  state_population
0             Guam  2021             49225
1             Guam  2022             48342
2             Guam  2023             47521
3             Guam  2024             43544
4   Virgin Islands  2021             87223
5   Virgin Islands  2022             86507
6   Virgin Islands  2023             85701
7   Virgin Islands  2024             84905
8   American Samoa  2021             49225
9   American Samoa  2022             48342
10  American Samoa  2023             47521
11  American Samoa  2024             46765

In [35]:
df_population = pd.concat([df_states_long, df_territories], ignore_index=True)

df_enriched = df.merge(
        df_population,
        on=["state_name", "year"],
        how="left",
        validate="many_to_one"
    )
df_enriched

,file_id,bh_index,ori,incident_number,incident_date,data_source,year,quarter,month,day_of_week,is_weekend,total_victims,num_adult_victims,num_juvenile_victims,total_offenders,num_adult_offenders,num_juvenile_offenders,victim_offender_ratio,offender_race,offender_ethnicity,offense_1,offense_1_severity,num_victims_1,victim_types_1,location_1,bias_motivation_1a,bias_1a_category,bias_motivation_1b,bias_1b_category,bias_motivation_1c,bias_1c_category,bias_motivation_1d,bias_1d_category,bias_motivation_1e,bias_1e_category,offense_2,offense_2_severity,num_victims_2,victim_types_2,location_2,bias_motivation_2a,bias_2a_category,bias_motivation_2b,bias_2b_category,bias_motivation_2c,bias_2c_category,bias_motivation_2d,bias_2d_category,bias_motivation_2e,bias_2e_category,offense_3,offense_3_severity,num_victims_3,victim_types_3,location_3,bias_motivation_3a,bias_3a_category,bias_motivation_3b,bias_3b_category,bias_motivation_3c,bias_3c_category,bias_motivation_3d,bias_3d_category,offense_4,offense_4_severity,num_victims_4,victim_types_4,location_4,bias_motivation_4a,bias_4a_category,offense_5,offense_5_severity,num_victims_5,victim_types_5,location_5,bias_motivation_5a,bias_5a_category,ori_agency,state_code,state_abbr,state_name,agency_name,agency_type,date_ori_went_nibrs,master_file_year,city_name,is_core_city,population_group,country_division,country_region,judicial_district,current_population,state_q1_activity,state_q2_activity,state_q3_activity,state_q4_activity,fips_counties_1,fips_counties_2,fips_counties_3,fips_counties_4,state_population
0,2021,441,AL0520100,AL0520100-GM5B8LZG Q8F-0,2021-01-01,NIBRS Incident,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,Black or African American,Not Hispanic or Latino,Arson,Medium,1,Individual,Residence/Home,Anti-White,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,AL0520100,01,AL,Alabama,DECATUR,City,2021-01-01,2021,DECATUR,True,"Cities 50,000-99,999",East South Central,South,Northern,54240,Incident Report submitted,Zero-Report (no incident),Zero-Report (no incident),Zero-Report (no incident),103,083,None,None,5049196.0
1,2021,1065,AZ0080000,AZ0080000-V2-IYBRWSU72-0,2021-01-01,NIBRS Incident,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,Robbery,High,1,Individual,Residence/Home,Anti-Church of Jesus Christ (LDS),Religion,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,AZ0080000,02,AZ,Arizona,MOHAVE,County,2020-10-01,2021,KINGMAN,False,"MSA Counties 25,000-99,999",Mountain,West,All of the state,74698,Incident Report submitted,Incident Report submitted,Zero-Report (no incident),Zero-Report (no incident),015,None,None,None,7274078.0
2,2021,1482,CA0191900,CA0191900-0819PU72ZPX8-0,2021-01-01,Unknown,2021,Q1,1,Friday,False,2,2,0,1,1,0,2.0,White,Not Hispanic or Latino,Intimidation,Low,1,Individual,Residence/Home,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,CA0191900,04,CA,California,CERRITOS,City,NaT,2021,MONTEREY PARK,False,"Cities 25,000-49,999",Pacific,West,Central,48583,Incident Report submitted,Incident Report submitted,Zero-Report (no incident),Incident Report submitted,037,None,None,None,39142565.0
3,2021,1788,CA0331300,CA0331300-CN0BRVSQT28N-0,2021-01-01,Unknown,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,Aggravated Assault,High,1,Individual,Highway/Road/Alley,Anti-Black or African American,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,CA0331300,04,CA,California,RIVERSIDE,City,2023-01-01,2021,RIVERSIDE,True,"Cities 250,000-499,999",Pacific,West,Central,333437,Incident Report submitted,Incident Report submitted,Incident Report submitted,Incident Report submitted,065,None,None,None,39142565.0
4,2021,1864,CA0350100,CA0350100-NM-U72841AEM-0,2021-01-01,Unknown,2021,Q1,1,Friday,False,1,1,0,1,1,0,1.0,None,Hispanic or Latino,Intimidation,Low,1,Individual,Restaurant,Anti-Gay (Male),Sexual Orientation,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,CA0350100,04,CA,California,HOLLISTER,City,2021-02-01,2021,HOLLISTER,False,"Cities 25,000-49,999",Pacific,West,Northern,42505,Incident Report submitted,Zero-Report (no incident),Incident Report submitted,Zero-Report (no incident),069,None,None,None,39142565.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46670,2024,14776,NJ0151400,NJ0151400-2K-M46X2ID1A-0,2024-12-31,NIBRS Incident,2024,Q4,12,Tuesday,False,1,1,0,1,1,0,1.0,White,Not Hispanic or Latino,Intimidation,Low,1,Individual,Residence/Home,Anti-Hispanic or Latino,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,NJ0151400,29,NJ,New Jersey,LAKEWOOD TOWNSHIP,City,2021-01-01,2024,LAKEWOOD,True,"Cities 100,000-249,999",Middle Atlantic,Northeast,All of the state,144876,Incident Report submitted,Incident Report submitted,Incident Report submitted,Incident Report submitted,029,None,None,None,9500851.0
46671,2024,15568,NY0303000,NY0303000-380J4IOYU6ST-0,2024-12-31,NIBRS Incident,2024,Q4,12,Tuesday,False,1,1,0,1,1,0,1.0,Asian,Not Hispanic or Latino,Intimidation,Low,1,Individual,Residence/Home,Anti-Jewish,Religion,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,NY0303000,31,NY,New York,NEW YORK,City,2023-01-01,2024,NEW YORK,True,"Cities 1,000,000+",Middle Atlantic,Northeast,Eastern,8299271,Incident Report submitted,Incident Report submitted,Incident Report submitted,Incident Report submitted,None,None,None,None,19867248.0
46672,2024,17065,OH0510100,OH0510100-WU02K3H76KPT-0,2024-12-31,NIBRS Incident,2024,Q4,12,Tuesday,False,1,1,0,0,0,0,<NA>,None,None,Motor Vehicle Theft,Medium,1,Individual,Residence/Home,Anti-White,Race/Ethnicity,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,OH0510100,34,OH,Ohio,MARION,City,1999-05-01,2024,MARION,False,"Cities 25,000-49,999",East North Central,North Central,Northern,35373,Zero-Report (no incident),Zero-Report (no incident),Zero-Report (no incident),Incident Report submitted,101,None,None,None,11883304.0
46673,2024,22464,TX0610600,TX0610600-V-PUV-AG0W5-0,2024-12-31,NIBRS Incident,2024,Q4,12,Tuesday,False,2,2,0,1,1,0,2.0,Black or African American,Not Hispanic or Latino,Intimidation,Low,2,Individual,Residence/Home,Anti-Gay (Male),Sexual Orientation,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,TX0610600,42,TX,Texas,LEWISVILLE,City,2002-01-01,2024,LEWISVILLE,False,"Cities 100,000-249,999",West South Central,South,Eastern,136046,Zero-Report (no incident),Incident Report submitted,Incident Report submitted,Incident Report submitted,121,113,None,None,31290831.0
46674,2024,24675,WA0080200,WA0080200-L849LUXPJD1A-0,2024-12-31,NIBRS Incident,2024,Q4,12,Tuesday,False,1,1,0,1,1,0,1.0,White,None,Intimidation,Low,1,Individual,Cyberspace,Anti-Black or African American,Race/Ethnicity,Anti-Asian,Race/Ethnicity,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,None,None,None,None,WA0080200,46,WA,Washington,LONGVIEW,City,2010-05-01,2024,LONGVIEW,True,"Cities 25,000-49,999",Pacific,West,Western,37944,Zero-Report (no incident),Incident Report submitted,Incident Report submitted,Incident Report submitted,015,None,None,None,7958180.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46675 entries, 0 to 46674
Data columns (total 100 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   file_id                 46675 non-null  object
 1   bh_index                46675 non-null  int64
 2   ori                     46675 non-null  object
 3   incident_number         46675 non-null  object
 4   incident_date           46675 non-null  datetime64[ns]
 5   data_source             46675 non-null  object
 6   year                    46675 non-null  int32
 7   quarter                 46675 non-null  object
 8   month                   46675 non-null  int32
 9   day_of_week             46675 non-null  category
 10  is_weekend              46675 non-null  bool
 11  total_victims           46675 non-null  Int64
 12  num_adult_victims       46675 non-null  Int64
 13  num_juvenile_victims    46675 non-null  Int64
 14  total_offenders         46675 non-null  Int64
 15  num_adult_offenders     46675 non-null  Int64
 16  num_juvenile_offenders  46675 non-null  Int64
 17  victim_offender_ratio   34643 non-null  Float64
 18  offender_race           27126 non-null  object
 19  offender_ethnicity      16603 non-null  object
 20  offense_1               46673 non-null  object
 21  offense_1_severity      46588 non-null  object
 22  num_victims_1           46675 non-null  Int64
 23  victim_types_1          45747 non-null  object
 24  location_1              46675 non-null  object
 25  bias_motivation_1a      46675 non-null  object
 26  bias_1a_category        46675 non-null  object
 27  bias_motivation_1b      1395 non-null   object
 28  bias_1b_category        1395 non-null   object
 29  bias_motivation_1c      188 non-null    object
 30  bias_1c_category        188 non-null    object
 31  bias_motivation_1d      56 non-null     object
 32  bias_1d_category        56 non-null     object
 33  bias_motivation_1e      25 non-null     object
 34  bias_1e_category        25 non-null     object
 35  offense_2               1828 non-null   object
 36  offense_2_severity      1822 non-null   object
 37  num_victims_2           1828 non-null   Int64
 38  victim_types_2          1770 non-null   object
 39  location_2              1828 non-null   object
 40  bias_motivation_2a      1828 non-null   object
 41  bias_2a_category        1828 non-null   object
 42  bias_motivation_2b      48 non-null     object
 43  bias_2b_category        48 non-null     object
 44  bias_motivation_2c      8 non-null      object
 45  bias_2c_category        8 non-null      object
 46  bias_motivation_2d      5 non-null      object
 47  bias_2d_category        5 non-null      object
 48  bias_motivation_2e      2 non-null      object
 49  bias_2e_category        2 non-null      object
 50  offense_3               156 non-null    object
 51  offense_3_severity      156 non-null    object
 52  num_victims_3           156 non-null    Int64
 53  victim_types_3          153 non-null    object
 54  location_3              156 non-null    object
 55  bias_motivation_3a      156 non-null    object
 56  bias_3a_category        156 non-null    object
 57  bias_motivation_3b      3 non-null      object
 58  bias_3b_category        3 non-null      object
 59  bias_motivation_3c      1 non-null      object
 60  bias_3c_category        1 non-null      object
 61  bias_motivation_3d      1 non-null      object
 62  bias_3d_category        1 non-null      object
 63  offense_4               17 non-null     object
 64  offense_4_severity      17 non-null     object
 65  num_victims_4           17 non-null     Int64
 66  victim_types_4          17 non-null     object
 67  location_4              17 non-null     object
 68  bias_motivation_4a      17 non-null     object
 69  bias_4a_category        17 non-null     object
 70  offense_5               2 non-null      object
 71  offense_5_severity      2 non-null      object
 72  num_victims_5           2 non-null      Int64
 73  victim_types_5          2 non-null      object
 74  location_5              2 non-null      object
 75  bias_motivation_5a      2 non-null      object
 76  bias_5a_category        2 non-null      object
 77  ori_agency              46675 non-null  object
 78  state_code              46675 non-null  object
 79  state_abbr              46675 non-null  object
 80  state_name              46675 non-null  object
 81  agency_name             46675 non-null  object
 82  agency_type             46202 non-null  object
 83  date_ori_went_nibrs     42539 non-null  datetime64[ns]
 84  master_file_year        46675 non-null  object
 85  city_name               45648 non-null  object
 86  is_core_city            46202 non-null  object
 87  population_group        46202 non-null  object
 88  country_division        46675 non-null  object
 89  country_region          46202 non-null  object
 90  judicial_district       46225 non-null  object
 91  current_population      43189 non-null  Int64
 92  state_q1_activity       46675 non-null  object
 93  state_q2_activity       46675 non-null  object
 94  state_q3_activity       46675 non-null  object
 95  state_q4_activity       46675 non-null  object
 96  fips_counties_1         42642 non-null  object
 97  fips_counties_2         3166 non-null   object
 98  fips_counties_3         1394 non-null   object
 99  fips_counties_4         296 non-null    object
dtypes: Float64(1), Int64(12), bool(1), category(1), datetime64[ns](2), int32(2), int64(1), object(80)
memory usage: 35.2+ MB

In [42]:
df.select_dtypes(include='float64').columns

Index(['total_victims', 'num_adult_victims', 'num_juvenile_victims',
       'total_offenders', 'num_adult_offenders', 'num_juvenile_offenders',
       'victim_offender_ratio', 'num_victims_2', 'num_victims_3',
       'num_victims_4', 'num_victims_5', 'current_population'],
      dtype='object')

In [54]:
df['bias_motivation_3c'].nunique(dropna=False)

2

In [52]:
df['bias_motivation_3c'].value_counts()

bias_motivation_3c
Anti-Arab    1
Name: count, dtype: int64

In [53]:
df['bias_motivation_3c'].isnull().sum()

np.int64(46672)

In [22]:
len(df[df['current_population'] == 0])

0

In [6]:
pd.DataFrame(df[df['last_population'] == 0]['agency_type']).value_counts()

agency_type
City                             36092
County                            6877
University of Colleges            1382
State Police                       830
Local Police                       620
State Agency Enforcement Unit      277
Tribal / BIA Agencies              122
Name: count, dtype: int64

In [33]:
df.describe()

,bh_index,incident_date,year,month,total_victims,num_adult_victims,num_juvenile_victims,total_offenders,num_adult_offenders,num_juvenile_offenders,victim_offender_ratio,num_victims_1,num_victims_2,num_victims_3,num_victims_4,num_victims_5,date_ori_went_nibrs,current_population,last_population
count,46673.000000,46673,46673.000000,46673.000000,46673.000000,46673.000000,46673.000000,46673.000000,46673.000000,46673.000000,27400.000000,46673.000000,1828.000000,156.000000,17.000000,2.0,42538,4.667300e+04,46673.0
mean,11499.803505,2023-01-12 00:14:00.434512384,2022.521286,6.648512,0.965483,0.837229,0.128254,0.723095,0.581278,0.141816,1.033669,1.147751,1.207330,1.256410,1.176471,1.0,2015-06-17 18:32:36.989045248,8.407147e+05,0.0
min,0.000000,2021-01-01 00:00:00,2021.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.0,1985-01-01 00:00:00,0.000000e+00,0.0
25%,2891.000000,2022-01-26 00:00:00,2022.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,2010-01-01 00:00:00,2.216000e+04,0.0
50%,11344.000000,2023-01-15 00:00:00,2023.000000,7.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,2020-06-01 00:00:00,8.496000e+04,0.0
75%,16674.000000,2024-01-01 00:00:00,2024.000000,10.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,2021-11-01 00:00:00,6.261460e+05,0.0
max,26124.000000,2024-12-31 00:00:00,2024.000000,12.000000,40.000000,40.000000,23.000000,32.000000,15.000000,30.000000,25.000000,23.000000,23.000000,7.000000,3.000000,1.0,2025-01-01 00:00:00,8.475387e+06,0.0
std,7832.154026,NaN,1.106370,3.320585,0.821972,0.772814,0.461174,0.829108,0.698600,0.568204,0.769866,0.579310,0.849489,0.752388,0.528594,0.0,NaN,1.921697e+06,0.0

In [ ]:
df[''].value_counts()

is_weekend
False    34217
True     12456
Name: count, dtype: int64